//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceDataAccess.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hackathonteam289_dbEntities1 : DbContext
    {
        public hackathonteam289_dbEntities1()
            : base("name=hackathonteam289_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblInsuranceType> tblInsuranceTypes { get; set; }
        public virtual DbSet<tblMotorVehicleType> tblMotorVehicleTypes { get; set; }
        public virtual DbSet<tblMotorVendorDetail> tblMotorVendorDetails { get; set; }
        public virtual DbSet<tblCustomerDetail> tblCustomerDetails { get; set; }
        public virtual DbSet<tblMediPolicyDetail> tblMediPolicyDetails { get; set; }
        public virtual DbSet<tblMedTransactionDetail> tblMedTransactionDetails { get; set; }
        public virtual DbSet<tblMotorDetail> tblMotorDetails { get; set; }
        public virtual DbSet<tblMotorPaymentDetail> tblMotorPaymentDetails { get; set; }
        public virtual DbSet<tblMotorType> tblMotorTypes { get; set; }
        public virtual DbSet<tblNomineeDetail> tblNomineeDetails { get; set; }
        public virtual DbSet<tblMedicalCompany> tblMedicalCompanies { get; set; }
    }
}
