//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceDataAccess.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedTransactionDetail
    {
        public int ID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal AmountPaid { get; set; }
        public int PolicyId { get; set; }
        public int PaymentTerm { get; set; }
        public int PaymentMode { get; set; }
        public Nullable<long> ChequeNo { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    }
}
