//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceDataAccess.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMediPolicyDetail
    {
        public int ID { get; set; }
        public string PolicyCode { get; set; }
        public string PolicyName { get; set; }
        public decimal MaxAmount { get; set; }
        public int year { get; set; }
        public decimal MinAmount { get; set; }
        public int CompanyID { get; set; }
        public Nullable<decimal> PremiumAmount { get; set; }
    }
}
